export const AR_LABELS = {
  dashboard: 'لوحة التحكم',
  owners: 'الملاك',
  properties: 'العقارات',
  units: 'الوحدات',
  tenants: 'المستأجرون',
  contracts: 'العقود',
  invoices: 'الفواتير',
  payments: 'المدفوعات',
  expenses: 'المصروفات',
  receipts: 'الإيصالات',
  maintenance: 'الصيانة',
  reports: 'التقارير',
  settings: 'الإعدادات',
  ownersHub: 'مركز الملاك',
  analytics: 'التحليلات',
  users: 'المستخدمون',
  security: 'الأمان',
  notifications: 'الإشعارات',
  backup: 'النسخ الاحتياطي',
  automation: 'الأتمتة',
  integrations: 'التكاملات',
  financial: 'الحسابات المالية',
  arrears: 'المتأخرات',
  financialMaintenance: 'صيانة مالية',
  generalLedger: 'الأستاذ العام',
  chartOfAccounts: 'دليل الحسابات',
  leads: 'العملاء المحتملون',
  communicationHub: 'مركز التواصل',
  lands: 'الأراضي',
  commissions: 'العمولات',
  auditLog: 'سجل المراجعة',
  smartAssistant: 'المساعد الذكي',
  rentrixNavigationHub: 'مركز تنقل رينتريكس',
  collapse: 'طي',
  expand: 'توسيع',
  migrateAttachments: 'ترحيل المرفقات',
  paymentsAndExpenses: 'المدفوعات والمصروفات',
  cashflowOrchestration: 'تنسيق التدفق النقدي',
  page: 'الصفحة',
  of: 'من',
} as const;
