uploads = []
outputs = []

[[generated]]
id = "eB2Ahc7yjw-QUTffQIFoc"
uri = "file://artifacts/rentrix-mobile/assets/images/icon.png"
type = "image"
title = "rentrix mobile icon"

[[generated]]
id = "s-uQAcuQQNeJ3Dcfi4mmH"
uri = "file://artifacts/rentrix-pitch/public/hero.png"
type = "image"
title = "generated_image"
