import { Link } from '@tanstack/react-router';
import { Button } from '@/components/ui/button';
import { DataErrorScreen } from '@/components/data-error-screen';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { StatusBadge } from '@/components/ui/status-badge';
import { formatCompanyDate, formatCompanyMoney } from '@lib/format';
import type { DashboardSnapshot } from './dashboardSnapshot';
import { DashboardKpiCards } from './dashboard/DashboardKpiCards';
import { DashboardQuickActions } from './dashboard/DashboardQuickActions';
import { ExpiringContractsTable } from './dashboard/ExpiringContractsTable';
import { OverdueTenantsTable } from './dashboard/OverdueTenantsTable';
import { useDashboardData } from './dashboard/useDashboardData';

function ArrearsPanel({ totalOverdue, overdueInvoiceCount, averageDaysOverdue, buckets, isLoading, settings }: any) { return <Card><CardHeader><CardTitle>المتأخرات والتحصيل</CardTitle><CardDescription>ملخص فواتير متأخرة حسب أعمار الذمم المتاحة من التقارير الحالية.</CardDescription></CardHeader><CardContent className="space-y-5">{isLoading ? <Skeleton className="h-56 w-full" /> : null}{isLoading ? null : <><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-muted p-4"><p className="text-xs font-black text-muted-foreground">إجمالي المتأخرات</p><p className="mt-2 text-xl font-black" dir="ltr">{formatCompanyMoney(settings, totalOverdue)}</p></div><div className="rounded-2xl bg-muted p-4"><p className="text-xs font-black text-muted-foreground">فواتير متأخرة</p><p className="mt-2 text-xl font-black">{overdueInvoiceCount}</p></div></div><div className="rounded-2xl border border-border p-4"><div className="mb-3 flex items-center justify-between gap-3"><p className="font-black">أعمار الذمم</p><StatusBadge tone="gray">متوسط {Math.round(averageDaysOverdue)} يوم</StatusBadge></div><div className="space-y-3">{buckets.map((bucket: any) => <div key={bucket.label} className="flex items-center justify-between gap-3 rounded-xl bg-muted/60 px-3 py-2"><span className="text-sm font-bold text-muted-foreground">{bucket.label}</span><span className="text-sm font-black" dir="ltr">{formatCompanyMoney(settings, bucket.total)} · {bucket.invoiceCount}</span></div>)}</div></div><div className="flex flex-wrap gap-3"><Button asChild variant="secondary"><Link to="/arrears">فتح المتأخرات</Link></Button><Button asChild variant="secondary"><Link to="/invoices">فتح الفواتير</Link></Button></div></>}</CardContent></Card>; }
function MonthlyFinancialPanel({ snapshot, isLoading, settings }: Readonly<{ snapshot: DashboardSnapshot | undefined; isLoading: boolean; settings: any }>) { return <Card><CardHeader><CardTitle>نظرة مالية للشهر</CardTitle><CardDescription>ملخص يعتمد على تقرير الفترة المالية الحالي.</CardDescription></CardHeader><CardContent className="space-y-3">{isLoading ? <Skeleton className="h-48 w-full" /> : null}{isLoading ? null : <><div className="grid gap-3 md:grid-cols-2"><div className="flex items-center justify-between rounded-2xl bg-muted p-4"><span className="font-bold text-muted-foreground">المفوتر</span><span className="font-black" dir="ltr">{formatCompanyMoney(settings, snapshot?.financial.rentDue ?? 0)}</span></div><div className="flex items-center justify-between rounded-2xl bg-muted p-4"><span className="font-bold text-muted-foreground">المحصل</span><span className="font-black" dir="ltr">{formatCompanyMoney(settings, snapshot?.financial.collectedRent ?? 0)}</span></div><div className="flex items-center justify-between rounded-2xl bg-muted p-4"><span className="font-bold text-muted-foreground">المتبقي</span><span className="font-black" dir="ltr">{formatCompanyMoney(settings, snapshot?.financial.outstandingRent ?? 0)}</span></div><div className="flex items-center justify-between rounded-2xl bg-muted p-4"><span className="font-bold text-muted-foreground">صافي المركز</span><span className="font-black" dir="ltr">{formatCompanyMoney(settings, snapshot?.financial.netPosition ?? 0)}</span></div></div><Button asChild className="w-full"><Link to="/financials">فتح المالية</Link></Button></>}</CardContent></Card>; }
function DashboardErrorCard({ onRetry, error }: Readonly<{ onRetry: () => void; error: unknown }>) { return <div className="space-y-3"><DataErrorScreen title="تعذر تحميل بيانات لوحة التحكم" fallbackMessage="راجع اتصال Supabase أو صلاحيات التقارير الحالية ثم أعد المحاولة." error={error} /><Button type="button" variant="secondary" onClick={onRetry}>إعادة المحاولة</Button></div>; }

export function DashboardPage(_: Readonly<Record<string, never>>) {
  const { today, settings, snapshot, dashboardQuery, retryDashboard, expiringContracts, overdueTenantRows, kpiCards, buckets } = useDashboardData();

  return <div className="space-y-6"><section className="overflow-hidden rounded-3xl border border-border bg-card shadow-sm"><div className="grid gap-6 p-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-sm font-bold text-primary">لوحة تحكم Rentrix التشغيلية</p><h2 className="mt-3 max-w-3xl text-3xl font-black leading-tight">مركز متابعة العقارات والعقود والتحصيل من البيانات الحالية.</h2><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">تعرض اللوحة مؤشرات تشغيلية حقيقية من خدمات Supabase والتقارير الحالية بدون إضافة SQL أو RPCs أو مصادر legacy.</p></div><div className="rounded-3xl bg-primary/10 p-5 text-primary"><p className="text-xs font-black text-muted-foreground">حتى تاريخ</p><p className="mt-2 text-2xl font-black">{formatCompanyDate(settings, `${snapshot?.period.dateTo ?? today}T00:00:00`)}</p></div></div></section>{dashboardQuery.isError ? <DashboardErrorCard onRetry={retryDashboard} error={dashboardQuery.error} /> : null}<DashboardKpiCards cards={kpiCards} isLoading={dashboardQuery.isLoading} /><section className="grid gap-3 sm:gap-4 xl:grid-cols-3"><ExpiringContractsTable rows={expiringContracts} isLoading={dashboardQuery.isLoading} settings={settings} /><DashboardQuickActions /></section><section className="grid gap-3 sm:gap-4 xl:grid-cols-[1.15fr_0.85fr]"><ArrearsPanel totalOverdue={snapshot?.arrears.totalOverdue ?? 0} overdueInvoiceCount={snapshot?.arrears.overdueInvoiceCount ?? 0} averageDaysOverdue={snapshot?.arrears.averageDaysOverdue ?? 0} buckets={buckets} isLoading={dashboardQuery.isLoading} settings={settings} /><OverdueTenantsTable rows={overdueTenantRows} isLoading={dashboardQuery.isLoading} settings={settings} /></section><MonthlyFinancialPanel snapshot={snapshot} isLoading={dashboardQuery.isLoading} settings={settings} /></div>;
}
