// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rentrix-dashboard/CorporateCalm.tsx": () => import("../components/mockups/rentrix-dashboard/CorporateCalm.tsx"),
  "./components/mockups/rentrix-dashboard/DarkModern.tsx": () => import("../components/mockups/rentrix-dashboard/DarkModern.tsx"),
  "./components/mockups/rentrix-dashboard/EarthyWarmth.tsx": () => import("../components/mockups/rentrix-dashboard/EarthyWarmth.tsx")
};
