kind = "mobile"
previewPath = "/rentrix-mobile/"
title = "Rentrix Mobile"
version = "1.0.0"
id = "artifacts/rentrix-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/rentrix-mobile/" ]
localPort = 19996

[services.development]
run = "pnpm --filter @workspace/rentrix-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/rentrix-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/rentrix-mobile", "run", "serve" ]

[services.env]
PORT = "19996"
BASE_PATH = "/rentrix-mobile/"
