import type { Contract, Expense, Invoice, Person, Property, Unit } from '@/types/domain';
import { TableGenerator } from './TableGenerator';
import type { DocumentRequest, SignatureRole, UnifiedDocumentModel } from './types';

type Settings = { general?: { company?: { name?: string; address?: string; phone?: string } }; operational?: { currency?: string } };
type AppLikeDb = { settings: Settings; contracts: Contract[]; tenants: Person[]; units: Unit[]; properties: Property[] };
const fmtDate = (v?: string | null) => (v ? new Date(v).toLocaleDateString('en-GB') : '-');
const fmtDateTime = (v?: string | null) => (v ? new Date(v).toLocaleString('en-GB') : '-');
const currencyOf = (s?: Settings) => s?.operational?.currency || 'OMR';
const toMoney = (value: number, s?: Settings) => `${Number.isFinite(value) ? value.toFixed(3) : '0.000'} ${currencyOf(s)}`;
const baseHeader = (s: Settings, title: string, dateValue?: string, documentNo?: string) => ({ companyName: s.general?.company?.name || 'Rentrix', companyAddress: s.general?.company?.address, companyPhone: s.general?.company?.phone, title, documentNo, dateLabel: 'Date', dateValue, currency: currencyOf(s) });
const kpi = (label: string, value: unknown) => ({ label, value: value ? String(value) : '-' });
const footer = (signatures: SignatureRole[]) => ({ signatures, companyStampLabel: 'Company Stamp' });
const fileName = (prefix: string, id: string | null, fallback: string) => `${prefix}_${id || fallback}`;
const resolveContractContext = (db: AppLikeDb, contractId: string | null) => { const contract = db.contracts.find((c) => c.id === contractId); const tenant = contract ? db.tenants.find((t) => t.id === contract.tenant_id) : null; const unit = contract ? db.units.find((u) => u.id === contract.unit_id) : null; const property = unit ? db.properties.find((p) => p.id === unit.property_id) : null; return { contract, tenant, unit, property }; };

class DocumentEngine { build(request: DocumentRequest): UnifiedDocumentModel { switch (request.type) { case 'invoice': return this.buildInvoice(request.payload as { invoice: Invoice; db: AppLikeDb }); case 'contract': return this.buildContract(request.payload as { contract: Contract; db: AppLikeDb }); case 'expense_voucher': case 'payment': return this.buildExpense(request.payload as { expense: Expense; db: AppLikeDb }); default: throw new Error(`Unsupported document type: ${request.type}`);} }
  private buildInvoice({ invoice, db }: { invoice: Invoice; db: AppLikeDb }): UnifiedDocumentModel { const { tenant, unit, property } = resolveContractContext(db, invoice.contract_id); const total = (invoice.amount || 0); const paid = invoice.paid_amount || 0; const remaining = Math.max(0, total - paid); return { type: 'invoice', header: baseHeader(db.settings, 'Invoice', fmtDate(invoice.due_date), invoice.id.slice(0, 8)), kpis: [kpi('Tenant', tenant?.full_name), kpi('Unit', `${property?.title || '-'} / ${unit?.unit_number || '-'}`), kpi('Status', invoice.status)], tables: [TableGenerator.build(['Description', 'Amount'], [['Amount', toMoney(invoice.amount || 0, db.settings)], ['Tax', toMoney(0, db.settings)], ['Paid', toMoney(paid, db.settings)], ['Remaining', toMoney(remaining, db.settings)]], ['Total', toMoney(total, db.settings)])], footer: footer(['tenant', 'accountant', 'general_manager']), fileName: fileName('invoice', invoice.id.slice(0, 8), invoice.id) }; }
  private buildContract({ contract, db }: { contract: Contract; db: AppLikeDb }): UnifiedDocumentModel { const tenant = db.tenants.find((t) => t.id === contract.tenant_id); const unit = db.units.find((u) => u.id === contract.unit_id); const property = unit ? db.properties.find((p) => p.id === unit.property_id) : null; return { type: 'contract', header: baseHeader(db.settings, 'Contract', fmtDate(contract.start_date), contract.id.slice(0, 8)), kpis: [kpi('Tenant', tenant?.full_name), kpi('Unit', `${property?.title || '-'} / ${unit?.unit_number || '-'}`), kpi('Status', contract.status)], tables: [TableGenerator.build(['Field', 'Value'], [['Start', fmtDate(contract.start_date)], ['End', fmtDate(contract.end_date)], ['Rent', toMoney(contract.rent_amount || 0, db.settings)], ['Deposit', toMoney(0, db.settings)], ['Due Day', String(contract.payment_cycle || '-')]])], footer: footer(['owner', 'tenant', 'accountant', 'general_manager']), fileName: fileName('contract', contract.id.slice(0, 8), contract.id) }; }
  private buildExpense({ expense, db }: { expense: Expense; db: AppLikeDb }): UnifiedDocumentModel { return { type: 'expense_voucher', header: baseHeader(db.settings, 'Expense Voucher', fmtDateTime(expense.expense_date), expense.id.slice(0, 8)), kpis: [kpi('Category', expense.category), kpi('Status', '-'), kpi('Charged To', '-')], tables: [TableGenerator.build(['Field', 'Value'], [['Amount', toMoney(expense.amount || 0, db.settings)], ['Tax', toMoney(0, db.settings)], ['Reference', '-'], ['Notes', expense.description || '-']])], footer: footer(['accountant', 'general_manager']), fileName: fileName('expense', expense.id.slice(0, 8), expense.id) }; }
}

export const documentEngine = new DocumentEngine();
